services:
  fuzzy-api:
    hostname: fuzzy-api
    container_name: fuzzy-api
    image: ghcr.io/eightyfour-ovh/skeleton:main
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "8484:8000"  # nginx -> (php-fpm + prometheus)
    environment:
      - XDEBUG_MODE=coverage
    volumes:
      - ./:/app
    networks:
      eightyfour:

networks:
  eightyfour:
