# GitHub Actions for Fuzzy: PHP Analysis
name: PHP analysis, tests & build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  composer:
    name: Composer Analysis (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
        php-versions: ['8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, pgsql, pdo_mysql, pdo_pgsql, gmp, fileinfo, intl, opcache, xml, iconv, redis, mailparse
          coverage: xdebug
          tools: composer:v2

      - name: Restore cached files
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            vendor/
            var/cache/
          key: ${{ runner.os }}-PHP${{ matrix.php-versions }}-cache-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-PHP${{ matrix.php-versions }}-cache-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}-

      - name: Prepare `dev` environment
        run: |
          cp .env .env.local
          sed -i 's/APP_DEBUG=false/APP_DEBUG=true/g' .env.local
          sed -i 's/APP_ENV=prod/APP_ENV=dev/g' .env.local

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            vendor/
            var/cache/
          key: ${{ runner.os }}-PHP${{ matrix.php-versions }}-cache-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}

  build-and-push-image:
    # Uncomment when build is successful
    # if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
